include ../../extra.mk

STATIC_PIC_LIB_NOINST = ${QTWIDGETS_LIB_A}
STATIC_LIB_NOINST = ${QTWIDGETS_A}

SRCS = QtAction.mm	\
       QtApplication.mm	\
       QtWidget.mm

include ../../buildsys.mk

CPPFLAGS += -I. -I../QtCore -I../QtGui -I../common
