include ../../extra.mk

STATIC_PIC_LIB_NOINST = ${QTCORE_LIB_A}
STATIC_LIB_NOINST = ${QTCORE_A}

SRCS = QtChildEvent.mm		\
       QtCoreApplication.mm	\
       QtEvent.mm		\
       QtObject.mm		\
       QtThread.mm

include ../../buildsys.mk

CPPFLAGS += -I. -I../common
