include ../../extra.mk

STATIC_PIC_LIB_NOINST = ${QTGUI_LIB_A}
STATIC_LIB_NOINST = ${QTGUI_A}

SRCS = QtGUIApplication.mm	\
       QtPaintDevice.mm

include ../../buildsys.mk

CPPFLAGS += -I. -I../QtCore -I../common
