include ../../extra.mk

STATIC_PIC_LIB_NOINST = ${COMMON_LIB_A}
STATIC_LIB_NOINST = ${COMMON_A}

SRCS = OFDataArray+QByteArray.mm	\
       OFString+QString.mm

include ../../buildsys.mk

CPPFLAGS += -I. -I../QtCore
